DIR:
    DATA: 
        # Train, Validation, Augmentation and Test Data directories
        TRAIN_ROOT : '../neural-audio-fp-dataset/music/discotube_2023-188000/train/'
        VAL_ROOT : '../neural-audio-fp-dataset/music/discotube_2023-188000/val/'
        TEST_NOISE_ROOT : '../neural-audio-fp-dataset/music/discotube_2023-188000/test/noise/'
        TEST_CLEAN_QUERY_ROOT : '../neural-audio-fp-dataset/music/discotube_2023-188000/test/query_clean/'
        TEST_AUGMENTED_QUERY_ROOT : '../neural-audio-fp-dataset/music/discotube_2023-188000/test/query_augmented/'
                                  # You can provide empty string to TEST_AUGMENTED_QUERY_ROOT and set
                                  # TD_AUG.TS_BG_AUG=True and TD_AUG.TS_IR_AUG=True to enable
                                  # real-time augmentation during testing. 
        BG_ROOT : '../neural-audio-fp-dataset/aug/bg/'
        IR_ROOT : '../neural-audio-fp-dataset/aug/ir/'
    MODEL:
        # Directories to store the model, its training and checkpoints.
        LOG_ROOT : './logs/'
                    # Root directory where the checkpoint, tensorboard logs and
                    # images will be stored.
    EMBEDDINGS : './logs/emb/'
                # Root directory where the generated embeddings (uncompressed
                #  fingerprints) will be stored.

# Model hyper-parameters
MODEL:
    FS : 8000 # Sampling rate
    NORMALIZE_AUDIO: True # Scale the audio to [-1,1].
    DUR : 1. # Unit segment length in seconds.
    HOP : .5 # Hop-size of the segment window in seconds.
    STFT_WIN : 1024
    STFT_HOP : 256
    F_MIN : 300. # Frequency range.
    F_MAX : 4000. # Frequency range.
    N_MELS : 256 # Number of mel-frequency bins.
    EMB_SZ : 128  # Dimension of fingerprint, d in this paper.
    BN : 'layer_norm2d' # or 'batch_norm'
    SCALE_INPUTS: True # Scale the power mel-spectrogram to [-1,1].
    # NOTE:
    # - In the current version, modifying {FS, DUR, HOB, STFT WIN, STFT HOP}
    #   may cause the model to malfunction or cause input shape mismatch errors.
    #   In that case, you will need to modify the kernel size strides of Conv
    #   layers in 'model/fp/nnfp.py'.

# Training parameters
TRAIN:
    MAX_EPOCH : 100
    OPTIMIZER : 'Adam' # 'LAMB' or 'Adam'. LAMB for BSZ >= 240
    LR: # Learning rate and schedule
        INITIAL_RATE: 1e-4 # Initial learning rate. Usually in the range from 3e-5 to 1e-4 (BSZ < 1280)
        SCHEDULE : 'cos' # ['cos', 'cos-restart', 'None'].
        ALPHA : 1e-4 # Minimum learning rate value for decay as a fraction of INITIAL_RATE.
    TENSORBOARD : True
    SAVE_IMG : True # Saving similarity matrix generated by loss object.
    MINI_TEST_IN_TRAIN : True
    REDUCE_ITEMS_P : 100
                # Reduce training dataset size to percentage (%).
    # NOTE:
    # - MINI_TEST_IN_TRAIN=True performs mini-search-test using part of
    #   validation dataset at the end of every epoch in training.

BSZ: # Batch-size
    TR_BATCH_SZ : 120 # Training batch size N must be EVEN number.
    TR_N_ANCHOR : 60 # Usually N/2; N/5 for Triplet-loss. 
    VAL_BATCH_SZ : 120 # Must be EVEN number.
    VAL_N_ANCHOR : 60 # Usually N_val/2 
    TS_BATCH_SZ : 125

# Loss parameters
LOSS:
    LOSS_MODE : 'NTxent' # 'NTxent'(default) or 'Online-Triplet'(now-playing). 
    TAU : 0.05 # **NTXENT ONLY** temperature parameter 0. < TAU < 1. 
    MARGIN : 0.5 # **ONLINE-TRIPLET ONLY** 

# Time-domain augmentation parameters
TD_AUG:

    TR_BG_AUG : True
    TR_SNR : [0, 10] # Synthesize replicas using random SNR in the range of [MIN, MAX]. SNR in decibel.
    TR_IR_AUG : True

    VAL_BG_AUG : True # Validation set always follows this even in 'generate' command.
    VAL_SNR : [0, 10]
    VAL_IR_AUG: True

    # If True, augment the query segments in real time during testing. Otherwise,
    # does not apply augmentations. For simulating real life scenarios,
    # you should either augment the queries beforehand and provide 
    # augment=True option.
    TS_BG_AUG : False # We augment the test set beforehand.
    TS_SNR : [0, 10] # Active in real-time synthesis of test queries.
    TS_IR_AUG : False # We augment the test set beforehand.
    # If you set TD_AUG.TS_IR_AUG=True or 
    # TD_AUG.TS_BG_AUG=True, you must provide the corresponding augmentation. 
    # Setting them to True will not use the tracks in TEST_AUGMENTED_QUERY_ROOT

# Specaug parameters
SPEC_AUG:
    SPECAUG_CHAIN : ['cutout', 'horizontal'] # 'cutout', 'horizontal', 'vertical'
    SPECAUG_PROBS : 1.
    SPECAUG_N_HOLES : 1
    SPECAUG_HOLE_FILL : 'zeros' # one of {'min', 'zeros', 'random', [min_mag, max_mag]}

# Device setup
DEVICE:
    CPU_N_WORKERS : 8 # 4 for minimal system. 8 is recommended.
    CPU_MAX_QUEUE : 10 # 10 for minimal system. 20 is recommended.
